apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kostasapp1
  name: kostasapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kostasapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kostasapp1
    spec:
      containers:
      - image: kotsis/kostasapp:v1
        name: kostasapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
