apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kostasapp1
  name: kostasapp1
  namespace: kostas-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kostasapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kostasapp1
    spec:
      containers:
      - image: kotsis/kostasapp:v1
        name: kostasapp
        ports:
        - containerPort: 80
        resources: {}
status: {}

## adding service with NodePort
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kostassvc1
  name: kostassvc1
  namespace: kostas-project
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # need to match label of pod
    app: kostasapp1
  type: NodePort
status:
  loadBalancer: {}
